### ISSUE TITLE
xnalara imports all bones facing downwards

### ISSUE THREAD

**Issue by narbartor** [Valery-AA/XNALaraMesh-BL4_X#2] opened 2024-07-30 02:08 UTC
As the title says, when I import models it looks like this

![image](https://github.com/user-attachments/assets/24c73bf1-9432-46c6-b27a-eee82dad8583)

I also see an error that says
`Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\xps_tools.py", line 162, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 76, in getInputFilename
    status = xpsImport()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 165, in xpsImport
    hideUnusedBones([armature_ob])
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 285, in hideUnusedBones
    hideBonesByVertexGroup(armature_objs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 234, in hideBonesByVertexGroup
    recurBones(bone, vertexgroups, '')
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 240, in recurBones
    aux = recurBones(childBone, vertexgroups, '{} '.format(name))
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 240, in recurBones
    aux = recurBones(childBone, vertexgroups, '{} '.format(name))
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 240, in recurBones
    aux = recurBones(childBone, vertexgroups, '{} '.format(name))
  [Previous line repeated 3 more times]
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 245, in recurBones
    hideBone(bone)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh-BL4_X-master\import_xnalara_model.py", line 250, in hideBone
    bone.layers[1] = True
AttributeError: 'Bone' object has no attribute 'layers'
`

**Comment by Valery-AA** [comment] 2024-08-08 11:25
additionally, seems the code for handling armatures is abhorrent, this is going to take an enormous rewrite to make it work, expect an update that fixes this error not any sooner than a week

**Comment by Valery-AA** [comment] 2024-08-14 18:29
@narbartor hey, i attempted a fix at it, i don't know how the model i downloaded should look like so im not sure if i partially fixed it or fully fixed it

**Comment by narbartor** [comment] 2024-08-19 05:51
Im not super used to Git so I'm not quite sure where the 1.0.4 is. I can seem to only find the 1.0.3

**Comment by Valery-AA** [comment] 2024-08-19 08:50
> Im not super used to Git so I'm not quite sure where the 1.0.4 is. I can seem to only find the 1.0.3

@narbartor the release should be both available to download from the `release` page on the repository which is appropiately named v1.0.4, and in v1.0.4 i added support for auto updates meaning you won't even need to leave blender

here still the direct donwload link if you need https://github.com/Valery-AA/XNALaraMesh-BL4_X/releases/download/v1.0.2/XNALaraMesh-BL4_X.zip

**Comment by narbartor** [comment] 2024-08-19 08:56
It looks like that fixed the bone direction issue!

Though now that it's fixed, it lets me notice another issue.

A lot of xnalara models ive seen (Mostly when it comes to game ports) usually put in unused cluttery bones over in a different layer

![image](https://github.com/user-attachments/assets/568381ee-ea77-4cb2-96bf-aaad2c6c3ed7)


However with the 4.0 version forgoing layers and replacing it with collections basically removes it from all collections and has it all together in one. Making the armature full of those unused bones

![image](https://github.com/user-attachments/assets/79869275-8b80-4733-b2ab-71f5d44df46e)

**Comment by Valery-AA** [comment] 2024-08-19 09:00
that is another fix that i still have to figure out how to implement, the problem is that with collections you don't have anymore access to the bones within said collection like with layers, so you need to loop every single bone to check if they are in a collection do perform anything that is collection based, before it was `for bone in layer: do something` now it's 
`for bone in the_whole_armature: is bone the bone in specified collection? yes? then do something:` creating  performance nightmare

**Comment by narbartor** [comment] 2024-08-19 09:02
I see. I hope the best for you to be able to solve this

**Comment by Valery-AA** [comment] 2024-08-19 09:04
i'll close this since the main issue has been fixed and i'll make a dev bug notice about that collection problem👍

**Closed by Valery-AA** 2024-08-19 09:04 UTC
